services:
  mysql:
    image: mysql:8.4
    container_name: storage-helper-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: storage_helper
      MYSQL_ROOT_PASSWORD: tsy2004
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: storage-helper-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data:
